config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get '/about' => 'hello#about'

  get '/help' => 'hello#help'

  # get '/posts/new' => 'posts#new'
  #
  # post '/posts' => 'posts#create'
  #
  # get '/posts/edit' => 'posts#edit'
  #
  # get '/posts' => 'posts#index'
  #
  # get '/posts/:id' => 'posts#show'

  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# Create
  ## 사용자가 글을 작성하는 화면
  def new
    @post = Post.new
  end

  def create
    # params['post']
    @post = Post.new
    @post.title = params['post']['title']
    @post.content = params['post']['content']
    @post.save

    # redirect_to post_path(@post)
    redirect_to @post
  end

# Read
  ## 사용자에게 글 목록을 보여주는 화면
  def index
    @posts = Post.order(created_at: :DESC).page(params['page']).per(20)
  end

  ## 사용자가 글을 보는 화면
  def show
    @post = Post.find params['id']
  end

# Update
  ## 사용자가 글을 수정하는 화면
  def edit
    @post = Post.find params['id']
  end

  def update
    @post = Post.find params['id']
    @post.title = params['post']['title']
    @post.content = params['post']['content']
    @post.save

    redirect_to @post
  end

# Destroy
  def destroy
    @post = Post.find params['id']
    @post.destroy

    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(name)
    content_tag('span', '', class: "glyphicon glyphicon-#{name}")
  end
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/hello/about.html.erb
<h1>Hello#about</h1>
<p>Find me in app/views/hello/about.html.erb</p>

app/views/hello/help.html.erb
<h1>Hello#help</h1>
<p>Find me in app/views/hello/help.html.erb</p>

app/views/hello/home.html.erb
<h1>Memo App 입니다</h1>
<p>Find me in app/views/hello/home.html.erb</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MemoApp", root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New Post", new_post_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>*MemoApp*</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="container">
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= bootstrap_form_for(@post) do |f| %>
    <%= f.text_field :title, label: '제목' %>
    <%= f.text_area :content,
                    label: '내용',
                    class: 'tinymce',
                    rows: 15,
                    cols: 120 %>
    <%= tinymce %>
    <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<hr>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Hack Your Post</h1>

<div class="table-responsive">
  <table class="table table-fit">
    <thead>
      <tr>
        <th>title</th>
        <th>created_at</th>
      </tr>
    </thead>
    <% @posts.each do |post| %>
      <tbody>
        <td><%= link_to(post.title, post_path(post)) %></td>
        <td>
          <%= icon 'time' %>
          <%= local_time(post.created_at) %>
        </td>
      </tbody>
    <% end %>
  </table>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<hr />
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<hr>
<%= @post.content.html_safe %>
<hr>
<%= icon 'pencil' %>
<%= link_to '수정하기', edit_post_path %>
 |
<%= icon 'trash' %>
<%= link_to '삭제하기',
            post_path,
            method: :delete,
            data: { confirm: '정말로 삭제합니다.' } %>